### PR TITLE
Add Types

### PR DESCRIPTION
**Pull request by pierophp**
## Summary
I manually created the .d.ts file for the project.

I had to replace [rollup-plugin-terser](https://www.npmjs.com/package/rollup-plugin-terser) with @rollup/plugin-terser as this old Terser plugin is not fully compatible with the current rollup version.

I also have to install a new plugin: rollup-plugin-copy.

## Linked issue(s)
Issue #191

### CODE REVIEW

**Review by jankapunkt — CHANGES_REQUESTED** [review]
Hi @pierophp thanks a lot! Looks good so far. However, the CI fails with the following error:

```shell

Run npm ci
npm ERR! Cannot read property '@babel/core' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-08-23T04_31_28_253Z-debug.log
Error: Process completed with exit code 1.
```

https://github.com/jankapunkt/easy-speech/actions/runs/5942505634/job/16128513900?pr=192

Can you please investigate this?

**Comment by pierophp** [comment]
I'll take a look @jankapunkt

**Comment by pierophp** [comment]
I had a lint issue running it on my machine. I fixed it:
image

It's working for me now:
image

**Comment by jankapunkt** [comment]
@pierophp I'm not sure, why the CI fails and I found some more issues. I can either propose my changes in a review and you work them out or you can add me to the forked repo as collaborator and I add the changes myself there. How should we proceed?

**Comment by jankapunkt** [comment]
@pierophp I updated everything and got the CI passing, however I can't push it to your branch, so I moved it to a branch in this REPO and opened a PR here: https://github.com/jankapunkt/easy-speech/pull/195

Please review and let me know if this works for you now, then I can merge and publish the changes. Thanks a lot

**Pull request closed without merging**
